name: new_torchenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h0a891b7_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.14.6=py38ha65f79e_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cryptography=37.0.2=py38h2b5fc30_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_mkl
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=hf544144_3
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2022.1.0=hc2b9512_224
  - ncurses=6.3=h5eee18b_3
  - nettle=3.6=he412f7d_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1t=h7f8727e_0
  - pip=22.2.2=py38h06a4308_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.13=h12debd9_0
  - python_abi=3.8=2_cp38
  - pytorch=1.13.0=py3.8_cpu_0
  - pytorch-mutex=1.0=cpu
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=pyhd8ed1ab_1
  - setuptools=63.4.1=py38h06a4308_0
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.13.0=py38_cpu
  - typing_extensions=4.3.0=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - albumentations==1.3.0
    - coloredlogs==15.0.1
    - contourpy==1.0.5
    - cycler==0.11.0
    - cython==0.29.34
    - easydict==1.10
    - flatbuffers==23.3.3
    - fonttools==4.37.4
    - humanfriendly==10.0
    - imageio==2.22.1
    - insightface==0.7.3
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - kornia==0.6.9
    - loguru==0.7.0
    - matplotlib==3.6.1
    - mpmath==1.3.0
    - networkx==2.8.7
    - numpy==1.23.4
    - onnx==1.13.1
    - onnxruntime==1.14.1
    - opencv-python==4.6.0.66
    - opencv-python-headless==4.7.0.72
    - packaging==21.3
    - pillow==9.2.0
    - prettytable==3.7.0
    - protobuf==3.20.3
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pywavelets==1.4.1
    - pyyaml==6.0
    - qudida==0.0.4
    - scikit-image==0.19.3
    - scikit-learn==1.2.2
    - scipy==1.9.2
    - six==1.16.0
    - sympy==1.11.1
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - torch==1.12.1
    - torchfile==0.1.0
    - torchvision==0.13.1
    - tqdm==4.64.1
    - urllib3==1.26.12
    - wcwidth==0.2.6
    - yacs==0.1.8
prefix: /home/exx/.conda/envs/new_torchenv
